pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }

        stage('start docker-compose'){
            steps {
                echo "PATH is: $PATH"
                sh "docker-compose up --build -d"
           }
        }
    }
}